name: QA

on:
  push:
  workflow_call:

jobs:
  qa:
    name: Run QA tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
    - run: yarn install --ignore-scripts --frozen-lockfile
    - run: yarn test
